version: '3.8'
services:
    mysql:
        image: mysql:8.0
        container_name: miracle-mysql
        hostname: mysql
        ports:
            - 3306:3306
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: miracle
            MYSQL_USER: super
            MYSQL_PASSWORD: super123
        volumes:
            - './.docker/mysql/data:/var/lib/mysql'
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
    redis:
        image: redis:latest
        restart: always
        container_name: miracle-redis
        ports:
            - '6379:6379'
        volumes:
            - ./.docker/redis/d–∞ta:/root/redis
            - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_PASSWORD=super123
            - REDIS_PORT=6379
            - REDIS_DATABASES=16
